### ISSUE TITLE
TAS_Toolkit: Add Tooltips

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#104]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This issue is historic and won't be actioned in its current state. All new methods/changed methods should get documentation added as/when added, but at the moment demand/maintenance for this toolkit is low, so resource is not being allocated to it. If others wish to pick it up please feel free and raise discrete issues to tackle in subsequent PRs :smile:
