### ISSUE TITLE
TAS_Toolkit CleanPolyline use of parameters

### ISSUE THREAD

**Issue by MajaLindroth** [BHoM/TAS_Toolkit#221]
#### Description:
Input parameters are missing when using the CleanPolyline method. 

see issue : #1275 in the BHoM_Engine https://github.com/BHoM/BHoM_Engine/issues/1275

#### Expected behaviour:

That input parameters are used for the CleanPolyline method

**Comment by FraserGreenroyd** [comment]
This issue requires more work than the associated issue for XML_Toolkit, because TAS Toolkit does not contain any settings inputs to the adapter to control parameters for minimum segment length, etc.

Therefore this requires the following additions:
 - TAS Adapter settings object
 - TAS Adapter create object
 - Input of Adapter settings into all 3 TAS adapters
 - Use of settings throughout the code, mainly in the `CleanPolyline` but other places may benefit
