### ISSUE TITLE
TAS_Toolkit: Compliance of adapters

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/TAS_Toolkit#231]
There are a lot of private methods in the TASAdapers cs files.
In general for all adapters (this is a general rule that was true since the dawn of days, even before I joined, AFAIK), please consider that all efforts should be made to move methods that do not fall in CRUD or Adapter Action (Push, Pull, ...) categories in the Engine project, if they can. I believe that the only case where such methods cannot be moved would be to avoid a looping dependency (e.g. they'd need the Adapter type to work).
Additionally, starting from this Refactoring, the *Adapter.cs file should only contain the constructor, fields and properties strictly related to the Adapter.
I see there are a lot of private methods in the *Adapter.cs file that seem to possess all the qualities to make them Engine methods.

Taken from: https://github.com/BHoM/TAS_Toolkit/pull/230#pullrequestreview-344676139

**Comment by Tom-Kingstone** [comment]
List of things breaking compliance:
- Methods in *Adapter.cs files
- Private attributes in *Adapter.cs files (`m_adapterSettings` for instance)
- At least one Copyright header issue in Create.cs in TBDAdapter
- References to BHoM folders are C:/ProgramData/BHoM rather than $(ProgramData)

Ideas to restore compliance:
- [x] move methods out of *Adapter.cs files
- [x] create one or many `ActionConfig`s that will replace `m_adapterSettings` (and other private attributes)
- [x] fix copyright header
- [x] change references to BHoM folders to use $(ProgramData)
- [x] Do versioning for all changes which change the public facing objects (ie. removing FileSettings from the adapter)

Some possible other changes:
- [x] the methods in *Adapter.cs files seem to be duplicates of each other - apart from the fact that they act on different object types, the methods have the same name. Perhaps an interface method could be used.
- [x] Instead of having the adapters in separate projects, they could be all compiled into one (so there would be one TASAdapter.dll)
- [x] The TasTSDAdapter constructor is very unwieldy as well, a lot of these inputs will be handled with the `ActionConfig`, and in combination, any checks done on inputs should be done in the adapter actions, rather than in the constructor.
