### ISSUE TITLE
TasTSDAdapter structure question

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#89]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This is an issue of the reflection rather than anything we can actively do within the TAS Toolkit. It is the same for all toolkits. This issue should probably be raised within BHoM_UI for discussion with @adecler / @ZiolkowskiJakub / @epignatelli / @awakeman as they're the UI maintainers. Closing here as not an issue relevant to be fixed in this toolkit.
